from pathlib import Path

from script2 import build_tree


README_PATH = Path(__file__).resolve().parents[2] / "README.md"

TOC_START = "<!-- TOC:START - auto-generated by generate_toc.py, do not hand-edit -->"
TOC_END = "<!-- TOC:END -->"


def update_readme():
    text = README_PATH.read_text(encoding="utf-8")

    new_block = (
        f"{TOC_START}\n"
        f"## Table of Contents\n\n"
        f"{build_tree()}\n"
        f"{TOC_END}"
    )

    if TOC_START in text and TOC_END in text:
        start = text.index(TOC_START)
        end = text.index(TOC_END) + len(TOC_END)

        text = text[:start] + new_block + text[end:]
    else:
        text = text.rstrip() + "\n\n" + new_block + "\n"

    README_PATH.write_text(text, encoding="utf-8")

    print("README.md Table of Contents updated.")


if __name__ == "__main__":
    update_readme()