#!/usr/bin/env python3
"""
generate_toc.py

Regenerates the Table of Contents block in ca-chain README.md by walking the
numbered documentation folders and producing a nested markdown list.

Because the list is built from what's actually on disk, links can never
go stale or point at files that don't exist.

Usage:
    python generate_toc.py

Place this file at the root of the `documentation` repo, next to ca-chain README.md.
"""

import re
import sys
import urllib.parse
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    """Walk upward from `start` until a `.git` folder is found.
    Works no matter how deep this script lives (repo root, .github/scripts/, etc.)."""
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / ".git").exists():
            return candidate
    raise RuntimeError(
        f"Could not locate repo root: no .git folder found above {start}"
    )


REPO_ROOT = find_repo_root(Path(__file__).parent)
README_PATH = REPO_ROOT / "ca-chain README.md"

TOC_START = "<!-- TOC:START - auto-generated by generate_toc.py, do not hand-edit -->"
TOC_END = "<!-- TOC:END -->"

# Only top-level folders starting with a digit are walked (01-, 02-, ... 17-).
# This naturally excludes .git, .idea, imgs, and ORPHANS without listing them.
NUMERIC_DIR_PATTERN = re.compile(r"^\d")

# Top-level numeric folders excluded anyway (e.g. internal drafts, still "99-").
EXCLUDE_TOP_LEVEL_DIRS = {
    "99- INTERNAL & DRAFT sections (NOT publicly visible)",
}

# Individual files excluded even inside included folders (drafts, etc.)
EXCLUDE_FILE_PREFIXES = ("ZZZ",)


def md_link(path: Path) -> str:
    rel = path.relative_to(REPO_ROOT).as_posix()
    encoded = urllib.parse.quote(rel)
    title = path.stem
    return f"[{title}]({encoded})"


def walk(dir_path: Path, depth: int = 0) -> list[str]:
    lines = []
    entries = sorted(dir_path.iterdir(), key=lambda p: p.name.lower())

    if depth == 0:
        # Top level: only digit-prefixed folders, minus the explicit exclusions.
        # Loose root-level files (ca-chain README.md, HOW-TO-DOCUMENT.md, etc.) are
        # ignored entirely — only content inside numbered folders is listed.
        dirs = [
            e for e in entries
            if e.is_dir()
            and NUMERIC_DIR_PATTERN.match(e.name)
            and e.name not in EXCLUDE_TOP_LEVEL_DIRS
        ]
        files = []
    else:
        # Deeper levels: walk all subfolders (e.g. "A- Beginner Sessions").
        dirs = [e for e in entries if e.is_dir()]
        files = [
            e for e in entries
            if e.is_file()
            and e.suffix.lower() == ".md"
            and e.name.lower() != "readme.md"
            and not e.name.startswith(EXCLUDE_FILE_PREFIXES)
        ]

    indent = "  " * depth
    for f in files:
        lines.append(f"{indent}* {md_link(f)}")
    for d in dirs:
        lines.append(f"{indent}* **{d.name}**")
        lines.extend(walk(d, depth + 1))

    return lines


def build_toc() -> str:
    lines = ["## Table of Contents", ""]
    lines.extend(walk(REPO_ROOT))
    return "\n".join(lines)


def update_readme() -> None:
    if not README_PATH.exists():
        sys.exit(f"ca-chain README.md not found at detected repo root: {REPO_ROOT}")
    text = README_PATH.read_text(encoding="utf-8")
    new_block = f"{TOC_START}\n{build_toc()}\n{TOC_END}"

    if TOC_START in text and TOC_END in text:
        pattern = re.compile(re.escape(TOC_START) + r".*?" + re.escape(TOC_END), re.DOTALL)
        text = pattern.sub(new_block, text)
    else:
        text = text.rstrip() + f"\n\n{new_block}\n"

    README_PATH.write_text(text, encoding="utf-8")
    print("ca-chain README.md Table of Contents updated.")


if __name__ == "__main__":
    update_readme()