# deployment for a Master that consists of manually set external & local IP, as well as authentication enabled
docker run --network host --name al-master-node --rm \
    -e NODE_TYPE=master \
    -e EXTERNAL_IP=10.0.0.212 \
    -e LOCAL_IP=10.0.0.212 \
    -e AUTHENTICATION=true \
    -e USERNAME=anylog \
    -e PASSWORD=demo \
    -e AUTH_TYPE=admin \
    -e ANYLOG_SERVER_PORT=2048 \
    -e ANYLOG_REST_PORT=2049 \
    -e MASTER_NODE=10.0.0.212:2048 \
    -e DB_TYPE=psql \
    -e DB_USER=anylog@127.0.0.1:demo \
    -e DB_PORT=5432 \
    -e SYNC_TIME="30 second" \
    -e COMPANY_NAME=AnyLog \
    -v al-master-anylog:/app/AnyLog-Network/anylog:rw \
    -v al-master-blockchain:/app/AnyLog-Network/blockchain:rw \
    -v al-master-data:/app/AnyLog-Network/data:rw \
    -v al-master-local-scripts:/app/AnyLog-Network/local_scripts:rw \
    -v al-master-scripts:/app/AnyLog-Network/scripts:rw \
    -d -it --detach-keys="ctrl-d" oshadmon/anylog:predevelop