# Single node running against SQLite
docker run --network host --name al-single-node --rm \
    -e NODE_TYPE=single-node \
    -e ANYLOG_SERVER_PORT=2050 \
    -e ANYLOG_REST_PORT=2051 \
    -e MASTER_NODE=10.0.0.212:2050 \
    -e DB_TYPE=sqlite \
    -e DB_USER=pi@127.0.0.1:razzburry \
    -e DB_PORT=5432 \
    -e DEFAULT_DBMS=demo \
    -e SYNC_TIME="30 second" \
    -e COMPANY_NAME=AnyLog \
    -e CLUSTER_NAME=new-cluster \
    -e NODE_NAME=single-node \
    -e ENABLE_PARTITION=true \
    -e PARTITION_COLUMN=timestamp \
    -e DROP_PARTITION=true \
    -e PARTITION_KEEP=30 \
    -e PARTITION_INTERVAL="7 day" \
    -e ENABLE_DATA_MONITOR=true \
    -e TABLE_NAME=* \
    -e INTERVAL_VALUE=10 \
    -e DATA_MONITOR_INTERVAL="1 minute" \
    -e DATA_MONITOR_COLUMN="value" \
    -v al-single-node-anylog:/app/AnyLog-Network/anylog:rw \
    -v al-single-node-blockchain:/app/AnyLog-Network/blockchain:rw \
    -v al-single-node-data:/app/AnyLog-Network/data:rw \
    -v al-single-node-local-scripts:/app/AnyLog-Network/local_scripts:rw \
    -v al-single-node-scripts:/app/AnyLog-Network/scripts:rw \
    -it --detach-keys="ctrl-d" oshadmon/anylog:predevelop